# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#   schedule: 
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '*/15 * * * *'   # Runs every 15 mins
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
  
    runs-on: ubuntu-latest
#     runs-on: self-hosted
#     container:
#        image: 547919350166.dkr.ecr.us-west-2.amazonaws.com/codegurureviewer-actions:latest
#        credentials:
#          username: AWS
#          password: ${{ secrets.ECR_PASSWORD }}       
         
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Dump Github content
      env:
        EVENT_METADATA: ${{ toJSON(github) }}
      run: echo "$EVENT_METADATA"

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ always() }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
        aws-region: us-east-1

      
    - name: ECR login
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: ECR login
      run: docker pull 776643825366.dkr.ecr.us-east-1.amazonaws.com/sariftestingrepo:latest


    # Extra step requied for private beta .. 
    - name: Checkout the action from a private repository
      uses: actions/checkout@v2
      if: ${{ always() }}
      with:
        repository: persongu/CICDSarifTesting
        ref: refs/heads/main
        token: ${{ secrets.TOKEN }}
        path: ./.github/persongu/CICDSarifTesting
        

    - name: AWS CodeGuru Reviewer
      uses: ./.github/persongu/CICDSarifTesting
      if: ${{ always() }}
      with:          
        source_path: . # Java source code root
        build_path: target # build artifact(s) directory
        s3_bucket: codeguru-reviewer-9876543 #name of s3 bucket to be used
        

    - name: Upload review result
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
